env:
    global:
        - PACKAGE="MagicTemplates"
        - SUBLIME_TEXT_VERSION="3"

matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests --coverage

after_success:
    - pip3 install python-coveralls;
    - pip3 install codecov;
    - coveralls
    - codecov

notifications:
    email: false
